AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RDS Proxy IaC

Parameters:
  Type: String
    Default: dev
    AllowedValues:
      - dev
      - hml
      - prd
  BusinessUnitName:
    Type: String
    Default: global
  PlatformName:
    Type: String
    Default: dockone
  ApplicationName:
    Type: String
    Default: app architecture
  ComponentName:
    Type: String
    Default: rdsproxy architecture
  PciClassificationName:
    Type: String
    Default: non-pci
    AllowedValues:
      - pci
      - pci-connected
      - non-pci
  PciScope:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  Owner:
    Type: String
    Default: architecture

Mappings:
  Network:
    dev:
      SgRDS: vpc-0df31a6e2d113d8b7
      SubnetAZA: subnet-0ca2d45be9d6ab5bc
      SubnetAZB: subnet-05d3e7f4611c12a23
      SubnetAZC: subnet-0b2b57acbb1da0623
    hml:
      SgRDS: sg-0eec7b010b760677d
      SubnetAZA: subnet-0fb3b86a8657a696f
      SubnetAZB: subnet-0fb6727ed0041b799
      SubnetAZC: subnet-0c45c1b6d9ba2cfc5
    prd:
      SgRDS: sg-0eec7b010b760677d
      SubnetAZA: subnet-0a0c6c1b76845ca8a
      SubnetAZB: subnet-0d2dc2da1fb208470
      SubnetAZC: subnet-0446d425f47765e5b

  RDS:
    dev:
      RDSIdentifier: db-arch-01
      RDSSecretManagerArn: "arn:aws:secretsmanager:us-east-2:792192516784:secret:992382474575_arch-rds-02-access-ncEwuy"
    hml:
      RDSIdentifier: db-arch-hml
      RDSSecretManagerArn: "arn:aws:secretsmanager:us-east-2:792192516784:secret:992382474575_arch-rds-02-access-ncEwuy"
    prd:
      RDSIdentifier: db-arch-prd
      RDSSecretManagerArn: "arn:aws:secretsmanager:us-east-2:792192516784:secret:992382474575_arch-rds-02-access-ncEwuy"

  Proxy:
    dev:  
      RDSProxyIdentifier: rds-proxy-db-arch-01
      RDSProxyIdleClientTimeout: 3600
      RDSProxyMaxConnectionsPercent: 90
      RDSProxyMaxIdleConnectionsPercent: 50
    hml:
      RDSProxyIdentifier: rds-proxy-db-arch-02-hml
      RDSProxyIdleClientTimeout: 3600
      RDSProxyMaxConnectionsPercent: 90
      RDSProxyMaxIdleConnectionsPercent: 50
    prd:
      RDSProxyIdentifier: rds-proxy-db-arch-02-prd
      RDSProxyIdleClientTimeout: 3600
      RDSProxyMaxConnectionsPercent: 90
      RDSProxyMaxIdleConnectionsPercent: 50

Resources:
  RDSProxy:
    Type: AWS::RDS::DBProxy
    Properties:
      DBProxyName: !FindInMap [Proxy, !Ref Env, RDSProxyIdentifier]
      Auth:
        - AuthScheme: SECRETS
          Description: arch-database-password
          IAMAuth: DISABLED
          SecretArn: !FindInMap [RDS, !Ref Env, RDSSecretManagerArn]
      EngineFamily: POSTGRESQL
      DebugLogging: true
      IdleClientTimeout: !FindInMap [Proxy, !Ref Env, RDSProxyIdleClientTimeout]
      RequireTLS: false
      RoleArn: !GetAtt RDSProxyRole.Arn
      VpcSecurityGroupIds:
        - !FindInMap [Network, !Ref Env, SgRDS]
      VpcSubnetIds:
        - !FindInMap [Network, !Ref Env, SubnetAZA]
        - !FindInMap [Network, !Ref Env, SubnetAZB]
        - !FindInMap [Network, !Ref Env, SubnetAZC]
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: name
          Value: kmsRdsS3Backup
        - Key: resource
          Value: DBProxy
        - Key: business_unit
          Value: !Ref BusinessUnitName
        - Key: platform
          Value: !Ref PlatformName
        - Key: application
          Value: !Ref ApplicationName
        - Key: component
          Value: !Ref ComponentName
        - Key: owner
          Value: !Ref Owner
        - Key: pci_classification
          Value: !Ref PciClassificationName
        - Key: pci_scope
          Value: !Ref PciScope
  
  RDSProxyRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: DbArchRdsProxyRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "rds.amazonaws.com"
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: DbArchRdsProxyPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                - "secretsmanager:GetSecretValue"
                - "secretsmanager:DescribeSecret"
                Resource: !FindInMap [RDS, !Ref Env, RDSSecretManagerArn]
                Effect: Allow
              - Action:
                - "kms:Decrypt"
                - "kms:DescribeKey"
                Resource: "*"
                Effect: Allow
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: name
          Value: db-arch-rds-proxy-role
        - Key: resource
          Value: Role
        - Key: business_unit
          Value: !Ref BusinessUnitName
        - Key: platform
          Value: !Ref PlatformName
        - Key: application
          Value: !Ref ApplicationName
        - Key: component
          Value: !Ref ComponentName
        - Key: owner
          Value: !Ref Owner
        - Key: pci_classification
          Value: !Ref PciClassificationName
        - Key: pci_scope
          Value: !Ref PciScope

  RDSProxyTargetGroup:
    Type: AWS::RDS::DBProxyTargetGroup
    Properties:
      TargetGroupName: default
      DBProxyName: !Ref RDSProxy
      DBInstanceIdentifiers: 
        - !FindInMap [ RDS, !Ref Env, RDSIdentifier ]
      ConnectionPoolConfigurationInfo:
        MaxConnectionsPercent: !FindInMap [Proxy, !Ref Env, RDSProxyMaxConnectionsPercent ]
        MaxIdleConnectionsPercent: !FindInMap [Proxy, !Ref Env, RDSProxyMaxIdleConnectionsPercent]

