AWSTemplateFormatVersion: "2010-09-09"
Description: Template Secret Manager and Custom KMS

Parameters:
  Versao:
    Type: String
    Default: 1.0

  SecretName:
    Description: Secret Name
    Type: String
    Default: 908671954593-rds-db-arch-01

  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - hml
      - prd
  BusinessUnitName:
    Type: String
    Default: global
  PlatformName:
    Type: String
    Default: dockone
  ApplicationName:
    Type: String
    Default: app architecture
  ComponentName:
    Type: String
    Default: secret rds architecture
  PciClassificationName:
    Type: String
    Default: non-pci
    AllowedValues:
      - pci
      - pci-connected
      - non-pci
  PciScope:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  Owner:
    Type: String
    Default: architecture

Resources:
  RDSKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "Custom KMS key for encrypting RDS Secrets Manager"
      EnableKeyRotation: false
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: name
          Value: !Ref SecretName
        - Key: resource
          Value: Key
        - Key: business_unit
          Value: !Ref BusinessUnitName
        - Key: platform
          Value: !Ref PlatformName
        - Key: application
          Value: !Ref ApplicationName
        - Key: component
          Value: !Ref ComponentName
        - Key: owner
          Value: !Ref Owner
        - Key: pci_classification
          Value: !Ref PciClassificationName
        - Key: pci_scope
          Value: !Ref PciScope

  RDSKmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName:  !Join ['', ['alias/',!Ref SecretName, "-kms"]] 
      TargetKeyId: !Ref RDSKmsKey 

  RDSSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Ref SecretName
      Description: "Secret Access Key ID"
      KmsKeyId: !Ref RDSKmsKey
      SecretString: '{"username":"postgre","password":"postgre","engine":"postgres","host":"db-arch-01.couoacqalfwt.us-east-2.rds.amazonaws.com","port":5432,"dbname":"architecture","dbInstanceIdentifier":"db-arch-01","kmsid":"7a39a66d-dccf-427d-b688-c4185aa51b66","accountid":"908671954593"}'
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: name
          Value: !Ref SecretName
        - Key: resource
          Value: SecretManager
        - Key: business_unit
          Value: !Ref BusinessUnitName
        - Key: platform
          Value: !Ref PlatformName
        - Key: application
          Value: !Ref ApplicationName
        - Key: component
          Value: !Ref ComponentName
        - Key: owner
          Value: !Ref Owner
        - Key: pci_classification
          Value: !Ref PciClassificationName
        - Key: pci_scope
          Value: !Ref PciScope

Outputs:
  RDSSecret:
    Value: !Ref RDSSecret
  RDSKmsKey:
    Value: !Ref RDSKmsKey
  RDSKmsKeytARN:
    Value: !GetAtt RDSKmsKey.Arn