AWSTemplateFormatVersion: 2010-09-09
Description: Stack CloudWatch Filtering Subscription - cw-sub-munin-eks-dev

Parameters:
  DestinationArn:
    Type: String
    Default: arn:aws:logs:us-east-2:908671954593:destination:PeopleFirehoseLogStreamDestination
  FilterName:
    Type: String
    Default: munin-eks-dev
  LogGroup:
    Type: String
    Default: "/dock/eks/munin-eks-dev"

Resources:
  SubscriptionFilter: 
    Type: AWS::Logs::SubscriptionFilter
    Properties: 
      LogGroupName: !Ref LogGroup
      Distribution: "Random"
      FilterName: !Ref FilterName
      FilterPattern: "" #"? levelname" #"{$.userIdentity.type = Root}"
      DestinationArn: !Ref DestinationArn