AWSTemplateFormatVersion: '2010-09-09'
Description: Athena table 

Parameters:
  S3BucketLocation:
    Type: String
    Default: s3://908671954593-rds-export-dev/tables/audit_account_balance
  AthenaDatabase:
    Type: String
    Default: audit

Resources:  
  AthenaParquetTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref AthenaDatabase
      TableInput:
        Name: audit_account_balance
        StorageDescriptor:
          Columns:
            - Name: id
              Type: string
            - Name: request_id
              Type: string
            - Name: user_session
              Type: string
            - Name: create_a
              Type: timestamp
            - Name: currency
              Type: string
            - Name: old_amount
              Type: float
            - Name: new_amount
              Type: float
          Location: !Ref S3BucketLocation
          InputFormat: "org.apache.hadoop.mapred.TextInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
          SerdeInfo:
            SerializationLibrary: "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
            Parameters:
              'field.delim': ','
              'skip.header.line.count': '1'
        TableType: "EXTERNAL_TABLE"
        Parameters:
          classification: "csv"
