AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sesh - API Gateway account.
Parameters:
  Versao:
    Type: String
    Default: 0
  Env:
    Type: String
Mappings:
  Throttle:
    DefaultRate:
      value: 1000
    DefaultBurst:
      value: 1000
  Tag:
    ServiceName:
      value: sesh
    SquadName:
      value: sre-banking
    SquadSlack:
      value: sre-huddle
    SquadMail:
      value: sre-banking
Resources:
  ApiGwAccountConfig:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
        - ApiGatewayLoggingRole
        - Arn
  ApiGatewayLoggingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
      - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
  SeshUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: SeshUsagePlan
      Description: UsagePlan to configuration Throttle in ApiGateway.
      Tags:
      - Key: env
        Value:
          Ref: Env
      - Key: service
        Value:
          Fn::FindInMap:
          - Tag
          - ServiceName
          - value
      - Key: stack
        Value:
          Fn::Sub: ${AWS::StackName}
      - Key: squad
        Value:
          Fn::FindInMap:
          - Tag
          - SquadName
          - value
      - Key: slack
        Value:
          Fn::FindInMap:
          - Tag
          - SquadSlack
          - value
      - Key: email
        Value:
          Fn::FindInMap:
          - Tag
          - SquadMail
          - value
      - Key: resource
        Value: usage-plan
      Throttle:
        BurstLimit:
          Fn::FindInMap:
          - Throttle
          - DefaultRate
          - value
        RateLimit:
          Fn::FindInMap:
          - Throttle
          - DefaultBurst
          - value
