AWSTemplateFormatVersion: '2010-09-09'
Description: Creation of VpcLink

Parameters:
  Versao:
    Type: String
    Default: 1.0
  Env:
    Type: String
    Default: dev
  VpcLinkName:
    Type: String
    Default: NLB-vpce-global-nlb
  IngressNLBARN:
    Type: String
    Default: arn:aws:elasticloadbalancing:us-east-2:908671954593:loadbalancer/net/vpce-global-nlb-dev/8d531d1119f30e59
  TemplateURL:
    Type: String
    Default: https://eliezerraj-908671954593-devops.s3.us-east-2.amazonaws.com/cf-templates/vpc-link-template.yaml

Mappings:
  Tag:
    Service:
      value: arch-eks-01
    Squad:
      value: architecture
    Slack:
      value: architecture
    Email:
      value: architecture
  
Resources:
  VpcLinkNLB:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Ref VpcLinkName
        LoadBalancerArn:
          Ref: IngressNLBARN
        Env:
          Ref: Env
        Service:
          Fn::FindInMap:
          - Tag
          - Service
          - value
        Slack:
          Fn::FindInMap:
          - Tag
          - Slack
          - value
        Squad:
          Fn::FindInMap:
          - Tag
          - Squad
          - value
        Email:
          Fn::FindInMap:
          - Tag
          - Email
          - value
      TemplateURL: !Ref TemplateURL

#Outputs:
#  VpcLinkArchEks01:
#    Description: Task excution VpcLink
#    Value:
#      Ref: VpcLinkNLB
#    Export:
#      Name: vpclink-arch-eks-01
