AWSTemplateFormatVersion: '2010-09-09'
Description: Template create s3 bucket v1.0 - 02/05/2025

Parameters:
  Versao:
    Type: String
    Default: 0
  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - hml
      - prd
  BusinessUnitName:
    Type: String
    Default: global
  ReplicationArnRole:
    Type: String
    Default: arn:aws:iam::908671954593:role/s3crr-908671954593-mtls-ca-v04-role
  TargetBucketName:
    Type: String
    Default: docktech-992382474575-truststore-mtls-v04
  SourceBucketName:
    Type: String
    Default: docktech-908671954593-truststore-mtls-v04
  PlatformName:
    Type: String
    Default: dockone
  ApplicationName:
    Type: String
    Default: app architecture
  ComponentName:
    Type: String
    Default: s3 bucket
  PciClassificationName:
    Type: String
    Default: non-pci
    AllowedValues:
      - pci
      - pci-connected
      - non-pci
  PciScope:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  Owner:
    Type: String
    Default: architecture
        
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref SourceBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: MoveToIntelligentTiering
            Status: Enabled
            Transitions:
              - StorageClass: INTELLIGENT_TIERING
                TransitionInDays: 7
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      VersioningConfiguration:
        Status: Enabled
      ReplicationConfiguration:
        Role: !Ref ReplicationArnRole
        Rules:
          - Id: MtlsCaReplicationRule
            Status: Enabled
            Priority: 1
            DeleteMarkerReplication:
              Status: Disabled
            Filter:
              Prefix: ""
            Destination:
              Bucket: !Sub arn:aws:s3:::${TargetBucketName}
              StorageClass: STANDARD
      Tags:
      - Key: env
        Value: !Ref Env
      - Key: stack
        Value: !Sub ${AWS::StackName}
      - Key: name
        Value: !Ref SourceBucketName
      - Key: resource
        Value: bucket
      - Key: business_unit
        Value: !Ref BusinessUnitName
      - Key: platform
        Value: !Ref PlatformName
      - Key: application
        Value: !Ref ApplicationName
      - Key: component
        Value: !Ref ComponentName
      - Key: owner
        Value: !Ref Owner
      - Key: pci_classification
        Value: !Ref PciClassificationName
      - Key: pci_scope
        Value: !Ref PciScope