AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create iam external analyzer

Parameters:
  Env:
    Description: Execution environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - hml
      - prd
  OwnerName:
    Type: String
    Default: architecture
  Component:
    Type: String
    Default: iam-role

Resources:
  AwsSupportRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "AWSSupportAccessRole-${AWS::AccountId}"  
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "support.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSSupportAccess

Outputs:
  AwsSupportRole:
    Value: !GetAtt 'AwsSupportRole.Arn'