AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an API Gateway Usage Plan

Parameters:
  Versao:
    Type: String
    Default: 0
  Env:
    Description: stack environment
    Type: String
    Default: dev
  ApiGwId:
    Type: String
    Default: k0ng1bdik7
  ApiGwStage:
    Type: String
    Default: Live

Mappings:
  Tags:
    owner:
      value: architecture

Resources:
  ApiGwUsagePlanT1:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: tier1
      Throttle:
        RateLimit: 6000
        BurstLimit: 1200
      ApiStages:
        - ApiId: !Ref ApiGwId
          Stage: !Ref ApiGwStage
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: owner
          Value: !FindInMap [Tags, owner, value]

  ApiGwUsagePlanT2:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: tier2
      Throttle:
        RateLimit: 3000
        BurstLimit: 600
      ApiStages:
        - ApiId: !Ref ApiGwId
          Stage: !Ref ApiGwStage
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: owner
          Value: !FindInMap [Tags, owner, value]

  ApiGwUsagePlanT3:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: tier3
      Throttle:
        RateLimit: 1000
        BurstLimit: 200
      ApiStages:
        - ApiId: !Ref ApiGwId
          Stage: !Ref ApiGwStage
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: owner
          Value: !FindInMap [Tags, owner, value]

  ApiGwUsagePlanT4:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: tier4
      Throttle:
        RateLimit: 10
        BurstLimit: 2
      ApiStages:
        - ApiId: !Ref ApiGwId
          Stage: !Ref ApiGwStage
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: owner
          Value: !FindInMap [Tags, owner, value]

  ApiGwApiKeyT1:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: tier1
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ApiGwId
          StageName: !Ref ApiGwStage
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: owner
          Value: !FindInMap [Tags, owner, value]

  ApiGwApiKeyT2:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: tier2
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ApiGwId
          StageName: !Ref ApiGwStage
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: owner
          Value: !FindInMap [Tags, owner, value]

  ApiGwApiKeyT3:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: tier3
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ApiGwId
          StageName: !Ref ApiGwStage
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: owner
          Value: !FindInMap [Tags, owner, value]

  ApiGwApiKeyT4:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: tier4
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ApiGwId
          StageName: !Ref ApiGwStage
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: owner
          Value: !FindInMap [Tags, owner, value]

  ApiGwUsagePlanKeyT1:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiGwApiKeyT1
      KeyType: API_KEY
      UsagePlanId: !Ref ApiGwUsagePlanT1

  ApiGwUsagePlanKeyT2:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiGwApiKeyT2
      KeyType: API_KEY
      UsagePlanId: !Ref ApiGwUsagePlanT2

  ApiGwUsagePlanKeyT3:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiGwApiKeyT3
      KeyType: API_KEY
      UsagePlanId: !Ref ApiGwUsagePlanT3

  ApiGwUsagePlanKeyT4:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiGwApiKeyT4
      KeyType: API_KEY
      UsagePlanId: !Ref ApiGwUsagePlanT4

Outputs:
  ApiGwUsagePlanKeyT1:
    Value: !Ref ApiGwUsagePlanKeyT1
  ApiGwUsagePlanKeyT2:
    Value: !Ref ApiGwUsagePlanKeyT2
  ApiGwUsagePlanKeyT3:
    Value: !Ref ApiGwUsagePlanKeyT3
  ApiGwUsagePlanKeyT4:
    Value: !Ref ApiGwUsagePlanKeyT4