AWSTemplateFormatVersion: "2010-09-09"
Description: "Create DynamoDB"

Parameters:
  DynamoDBTableName:
    Type: String
    Default: table-name
  ReadCapacityUnits:
    Type: Number
    Default: 1
  WriteCapacityUnits:
    Type: Number
    Default: 1
  IsTimeToLive:
    Type: String
    AllowedValues: [ true, false ]
    Default: true

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBTableName
      AttributeDefinitions:
        -
          AttributeName: 'id'
          AttributeType: S
        -
          AttributeName: 'sk'
          AttributeType: S
      KeySchema:
        -
          AttributeName: 'id'
          KeyType: HASH
        -
          AttributeName: 'sk'
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits:  !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits
      TimeToLiveSpecification:
        AttributeName: TimeToLive
        Enabled: !Ref IsTimeToLive
      Tags:
        - Key: Name
          Value: !Ref DynamoDBTableName

Outputs:
  DynamoDBTable:
    Value: !Ref DynamoDBTableName