AWSTemplateFormatVersion: "2010-09-09"
Description: "Database definitions for Falcon Connector application"

Parameters:
  DefaultBillingMode:
    Type: String
    Default: PAY_PER_REQUEST
    AllowedValues:
      - PROVISIONED
      - PAY_PER_REQUEST

  Env:
    Type: String
    AllowedValues:
      - dev
      - hml
      - prd

  Versao:
    Type: String

Resources:
  FalconConnectorSetupsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: falconConnector.setups
      BillingMode: !Ref DefaultBillingMode
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: service
          Value: falcon-listener
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: squad
          Value: squad-horus
        - Key: slack
          Value: priv-squad-horus
        - Key: email
          Value: squad-horus
        - Key: resource
          Value: dynamo

      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: clientId
          AttributeType: S

      KeySchema:
        - AttributeName: id
          KeyType: HASH

      GlobalSecondaryIndexes:
        - IndexName: clientId-idx
          KeySchema:
            - AttributeName: clientId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  FalconConnectorInputEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: falconConnector.inputEvents
      BillingMode: !Ref DefaultBillingMode
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: service
          Value: falcon-listener
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: squad
          Value: squad-horus
        - Key: slack
          Value: priv-squad-horus
        - Key: email
          Value: squad-horus
        - Key: resource
          Value: dynamo

      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: type
          AttributeType: S
        - AttributeName: dateCreation
          AttributeType: S

      KeySchema:
        - AttributeName: id
          KeyType: HASH

      GlobalSecondaryIndexes:
        - IndexName: type-idx
          KeySchema:
            - AttributeName: type
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: dateCreation-idx
          KeySchema:
            - AttributeName: dateCreation
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  FalconConnectorPersonsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: falconConnector.persons
      BillingMode: !Ref DefaultBillingMode
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: service
          Value: falcon-listener
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: squad
          Value: squad-horus
        - Key: slack
          Value: priv-squad-horus
        - Key: email
          Value: squad-horus
        - Key: resource
          Value: dynamo

      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: personId
          AttributeType: S
        - AttributeName: eventId
          AttributeType: S

      KeySchema:
        - AttributeName: id
          KeyType: HASH

      GlobalSecondaryIndexes:
        - IndexName: personId-idx
          KeySchema:
            - AttributeName: personId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: eventId-idx
          KeySchema:
            - AttributeName: eventId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  FalconConnectorCardsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: falconConnector.cards
      BillingMode: !Ref DefaultBillingMode
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: service
          Value: falcon-listener
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: squad
          Value: squad-horus
        - Key: slack
          Value: priv-squad-horus
        - Key: email
          Value: squad-horus
        - Key: resource
          Value: dynamo

      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: cardId
          AttributeType: S
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: accountId
          AttributeType: S
        - AttributeName: personId
          AttributeType: S

      KeySchema:
        - AttributeName: id
          KeyType: HASH

      GlobalSecondaryIndexes:
        - IndexName: cardId-idx
          KeySchema:
            - AttributeName: cardId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: eventId-idx
          KeySchema:
            - AttributeName: eventId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: accountId-idx
          KeySchema:
            - AttributeName: accountId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: personId-idx
          KeySchema:
            - AttributeName: personId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  FalconConnectorAccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: falconConnector.accounts
      BillingMode: !Ref DefaultBillingMode
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: service
          Value: falcon-listener
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: squad
          Value: squad-horus
        - Key: slack
          Value: priv-squad-horus
        - Key: email
          Value: squad-horus
        - Key: resource
          Value: dynamo
    
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: accountId
          AttributeType: S
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: personId
          AttributeType: S

      KeySchema:
        - AttributeName: id
          KeyType: HASH

      GlobalSecondaryIndexes:
        - IndexName: accountId-idx
          KeySchema:
            - AttributeName: accountId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: eventId-idx
          KeySchema:
            - AttributeName: eventId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: personId-idx
          KeySchema:
            - AttributeName: personId
              KeyType: HASH
          Projection:
            ProjectionType: ALL