AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda template

Parameters:
  FunctionLambdaName:
    Type: String
    Default: lambda-name
  HandlerName:
    Type: String
    Description: Handler Name
    Default: main
  Timeout:
    Type: Number
    Description: Timeout in seconds
    Default: 3
  S3BucketParam:
    Type: String 
    Default: account-a-884069944685-artifacts
  S3KeyParam:
    Type: String 
    Default: lambda-card-tenant/main.zip
  ManagedPolicyParameterOne:
    Type: String 
    Default: arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
  ManagedPolicyParameterTwo:
    Type: String 
    Default: arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess
  ManagedPolicyParameterThree:
    Type: String 
    Default: arn:aws:iam::884069944685:policy/DynamoDB-Fine-Grained-card-tenant
  Runtime:
    Type: String
    Description: Runtime Environment name e.g nodejs, java8
    AllowedPattern: ^(go 1.x)$
    ConstraintDescription: must be a valid environment (go 1.x)

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns: 
        - !Ref ManagedPolicyParameterOne
        - !Ref ManagedPolicyParameterTwo
        - !Ref ManagedPolicyParameterThree
      Policies:
      - PolicyName: lambda_policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "s3:*"
            Resource: "*"
          - Effect: Allow
            Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
            - "logs:PutLogEvents"
            Resource: "*"

  LambdaFunction: 
    Type: "AWS::Lambda::Function"
    Properties: 
      FunctionName: !Ref FunctionLambdaName
      Handler: !Ref HandlerName
      Timeout: !Ref Timeout
      Runtime: !Ref Runtime
      Role: 
        Fn::GetAtt: 
          - "LambdaExecutionRole"
          - "Arn"
      Runtime: "go1.x"
      Code: 
        S3Bucket: !Ref S3BucketParam
        S3Key: !Ref S3KeyParam
      Tags:
      - Key: Name
        Value: !Ref FunctionLambdaName
  VersionLambda:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref LambdaFunction
      Description: version Live
  AliasLambda:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref LambdaFunction
      FunctionVersion: !GetAtt VersionLambda.Version
      Name: LIVE

Outputs:
  LambdaFunctionARN:
    Value: !GetAtt 'LambdaFunction.Arn'