AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Policy Secret Manage

Parameters:
  Versao:
    Type: String
    Default: 1.0
  Env:
    Description: Execution environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - hml
      - prd
  ARNSecretManager:
    Type: String
    Default: arn:aws:secretsmanager:us-east-2:184397147467:secret:EchoRMQClusterAccess-HoppIa
  RoleAssociation:
    Type: String
    Default: EchoRMQClusterRole

Resources:
  customPolicyForSecretManager:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: customSecretRMQPolicy 
      Description: Customer managed policy for read access secret manager
      Path: '/'
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 
              - 'secretsmanager:GetSecretValue'
              - 'secretsmanager:DescribeSecret'
            Resource: !Ref ARNSecretManager
      Roles: # attach this policy to the list of existing roles
          - !Ref RoleAssociation
