AWSTemplateFormatVersion: '2010-09-09'
Description: Template create s3 bucket/policy

Parameters:
  S3BucketName:
    Description: Bucket Name
    Type: String
  LambdaArnOne:
    Description: Inform the lambda ARN
    Type: String
    Default: ""

Conditions:
  IsLambdaArnOneInformed: !Not [!Equals [ !Ref LambdaArnOne, "" ]]

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      Tags:
      - Key: Name
        Value: !Join ['', [!Ref S3BucketName, "-Bucket"]]

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:*
            Resource:
              - !Sub arn:aws:s3:::${S3Bucket}
              - !Sub arn:aws:s3:::${S3Bucket}/*
            Principal:
              '*'
            #  - !If [ IsLambdaArnOneInformed, !Ref LambdaArnOne, '*' ]

Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: The name of the bucket
  BucketArn: 
    Value: !GetAtt S3Bucket.Arn
    Description: The buckey ARN