AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: RMQ Cluster Secret

Parameters:
  Versao:
    Type: String
    Default: 1.0
  Env:
    Description: Execution environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - hml
      - prd

Conditions:
  IsPrd: !Equals 
    - !Ref Env
    - prd

Mappings:
  Tag:
    Service:
      value: echo-rmq-cluster
    Squad:
      value: squad-zion
    Slack:
      value: arch-zio
    Email:
      value: zio

Resources:
  RMQClusterSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: EchoRMQClusterAccess
      Description: "This secret a secret to access EKS RMQ Cluster "
      GenerateSecretString:
        SecretStringTemplate: '{"RMQ_USER": "guest", "RMQ_URL": "amqp://guest:guest@172.20.244.153:5672/" }'
        GenerateStringKey: "RMQ_PASS"
        PasswordLength: 10
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: service
          Value: !FindInMap [Tag, Service, value]
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: squad
          Value: !FindInMap [Tag, Squad, value]
        - Key: slack
          Value: !FindInMap [Tag, Slack, value]
        - Key: email
          Value: !FindInMap [Tag, Email, value]
        - Key: resource
          Value: EchoRMQClusterAccess