AWSTemplateFormatVersion: 2010-09-09
Description: Creation of NLB for the Global API project

Parameters:
  Versao:
    Type: String
  Env:
    Type: String
  VPCEndpointIPs:
    Default: 10.214.72.61,10.214.187.10,10.214.241.14
    Type: CommaDelimitedList      
  TemplateURL:
    Type: String
    Default: https://eliezerraj-908671954593-devops.s3.us-east-2.amazonaws.com/cf-templates/nlb-template-vpce.yaml

Mappings:
  Network:
    dev:
      VpcId: vpc-0df31a6e2d113d8b7
      VpcCidr: 10.214.0.0/16
      SubnetAZA: subnet-0ca2d45be9d6ab5bc
      SubnetAZB: subnet-0b2b57acbb1da0623
      SubnetAZC: subnet-05d3e7f4611c12a23
      CertificateArn: arn:aws:acm:us-east-2:908671954593:certificate/a784955c-9a8b-4403-bea2-527035ab3782
      HostedZoneId: Z032031337N3G0ZYNJ75U
      DomainName: vpce.global.architecture.caradhras.io
        
  Tag:
    CloudProvider:
      value: aws
    Application:
      value: api-gateway-global
    BusinessUnitName:
      value: banking
    Component:
      value: api-gateway-global
    Owner:
      value: architecture
    Platform:
      value: architecture
  Nlb:
    Version:
      value: 1.0.0

Conditions:
  isPrd: !Equals [!Ref Env, prd]

Resources:
  Nlb:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        IpAddressType: ipv4
        LoadBalancerName: !Sub vpce-global-nlb-${Env}
        Scheme: internal
        LoadBalancerType: network
        AccessLogsEnable: false
        SubnetIds:
          !Join
          - ","
          - - !FindInMap [ Network, !Ref Env, SubnetAZA ]
            - !FindInMap [ Network, !Ref Env, SubnetAZB ] 
            - !FindInMap [ Network, !Ref Env, SubnetAZC ]
        HostedZoneId: !FindInMap [ Network, !Ref Env, HostedZoneId ]
        DomainName: !FindInMap [ Network, !Ref Env, DomainName ]
        Env: !Ref Env
        CloudProvider: !FindInMap [ Tag, CloudProvider, value ]
        Owner: !FindInMap [ Tag, Owner, value ]
        BusinessUnitName: !FindInMap [ Tag, BusinessUnitName, value ]
        Component: !FindInMap [ Tag, Component, value ]
        Application: !FindInMap [ Tag, Application, value ]
        PCIClassification: !If [isPrd, pci, non-pci]
        PCIScope: !If [isPrd, true, false]
        Platform: !FindInMap [ Tag, Platform, value ] 
        CustomDNS: false
      TemplateURL: !Ref TemplateURL

  GlobalVPCEndpointListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Order: 1
          TargetGroupArn: !Ref GlobalVPCEndpointTargets
          Type: forward
      LoadBalancerArn: 
        Fn::GetAtt: [Nlb, Outputs.LoadBalancerArn]
      Port: 443
      Certificates:
        - CertificateArn: !FindInMap [ Network, !Ref Env, CertificateArn ] 
      Protocol: TLS
      SslPolicy: ELBSecurityPolicy-TLS13-1-0-2021-06

  GlobalVPCEndpointTargets:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: global-vpcendpoint-tg
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 10
      HealthCheckPort: 443
      HealthCheckProtocol: TCP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Port: 443
      Protocol: TLS
      TargetType: ip
      Targets:
      - Id: !Select [ 0, !Ref VPCEndpointIPs ]
      - Id: !Select [ 1, !Ref VPCEndpointIPs ]
      - Id: !Select [ 2, !Ref VPCEndpointIPs ]
      VpcId: !FindInMap [ Network, !Ref Env, VpcId ] 
      Tags:
        - Key: Name
          Value: global-vpcendpoint-tg
        -
          Key: env
          Value: !Ref Env
        -
          Key: CloudProvider
          Value: !FindInMap [ Tag, CloudProvider, value ]
        -
          Key: stack
          Value: !Sub ${AWS::StackName}
        -
          Key: Application
          Value: !FindInMap [ Tag, Application, value ]
        -
          Key: BusinessUnitName
          Value: !FindInMap [ Tag, BusinessUnitName, value ]
        -
          Key: Owner
          Value: !FindInMap [ Tag, Owner, value ]
        -
          Key: Platform
          Value: !FindInMap [ Tag, Platform, value ]
        -
          Key: Component
          Value: global
        -
          Key: PCIClassification
          Value: !If [isPrd, pci, non-pci]
        -
          Key: PCIScope
          Value: !If [isPrd, true, false]