apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: addons-on-demand
spec:
  disruption:
    budgets:
      - nodes: 50%
        reasons:
          - Empty
          - Underutilized
          - Drifted
    consolidateAfter: 1m
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: 100
    memory: 200Gi
  template:
    metadata:
      labels:
        app: workers-addons
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: addons
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: capacity-spread
          operator: In
          values:
            - 1-od
            - 2-od
            - 3-od
            - 4-od
            - 5-od
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - t
            - c
            - m
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
            - micro
            - small
            - medium
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - us-east-2a
            - us-east-2b
            - us-east-2c
      terminationGracePeriod: 5m