AWSTemplateFormatVersion: '2010-09-09'
Description: Creation of VpcLink - Sesh
Parameters:
  Versao:
    Type: String
  Env:
    Type: String
  nlbnonpci:
    Type: String
Mappings:
  Tag:
    Service:
      value: sesh
    Squad:
      value: squad-sre-banking
    Slack:
      value: sre-huddle
    Email:
      value: sre-banking
  VpcLink:
    Version:
      value: 1.0.0
Resources:
  VpcLinkNonPci:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: Sesh-Non-Pci
        LoadBalancerArn:
          Ref: nlbnonpci
        Env:
          Ref: Env
        Service:
          Fn::FindInMap:
          - Tag
          - Service
          - value
        Slack:
          Fn::FindInMap:
          - Tag
          - Slack
          - value
        Squad:
          Fn::FindInMap:
          - Tag
          - Squad
          - value
        Email:
          Fn::FindInMap:
          - Tag
          - Email
          - value
      TemplateURL:
        Fn::Sub:
        - https://docktech-cloudformation-templates.s3.us-east-2.amazonaws.com/aws-cfn-vpclink-template/${version}/cloudformation-${version}.yml
        - version:
            Fn::FindInMap:
            - VpcLink
            - Version
            - value
Outputs:
  SeshVpcLinkNonPCI:
    Description: Task excution VpcLinkNonPCI
    Value:
      Ref: VpcLinkNonPci
    Export:
      Name: vpclinkseshnonpci
