AWSTemplateFormatVersion: '2010-09-09'
Description: Creation of VpcLink v1

Parameters:
  Versao:
    Type: String
    Default: 1.0
  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - hml
      - prd
  LoadBalanceARN:
    Type: String
    Default: arn:aws:elasticloadbalancing:us-east-2:908671954593:loadbalancer/net/nlb-vpce-eks-arch-02-dev/b3c3be15a9e94703
  TemplateURL:
    Type: String
    Default: https://s3.us-east-2.amazonaws.com/eliezerraj-908671954593-devops-us-east-2/cf-templates/vpc-link-template-v1.yaml

Mappings:
  Tag:
    Application:
      value: go-architecture
    PciClassification:
      value: false
    Component:
      value: vpc-link
    Owner:
      value: architecture
  
Resources:
  VpcLinkNLB03:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: NLB-vpce-eks-arch-02
        LoadBalancerArn:
          Ref: LoadBalanceARN
        Env:
          Ref: Env
        Application:
          Fn::FindInMap:
          - Tag
          - Application
          - value
        Component:
          Fn::FindInMap:
          - Tag
          - Component
          - value
        PciClassification:
          Fn::FindInMap:
          - Tag
          - PciClassification
          - value
        Owner:
          Fn::FindInMap:
          - Tag
          - Owner
          - value
      TemplateURL: !Ref TemplateURL