AWSTemplateFormatVersion: "2010-09-09"
Description: Template VpcLink v1

Parameters:
  Name:
    Description: Name this Vpc Link.
    Type: String
  LoadBalancerArn:
    Description: Load balancer ARN.  
    Type: String
  Env:
    Description: Environment.  
    Type: String
  Application:
    Type: String
  Component:
    Type: String
  PciClassification:
    Type: String
  Owner:
    Type: String
    
Resources:
  VpcLinkNLB03:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Description: !Join
        - ' '
        - - Vpc Link to use for integration this 
          - !Ref Name
          - with API REST      
      Name: !Ref Name
      TargetArns: 
        - !Ref LoadBalancerArn
      Tags:
        -
          Key: env
          Value: !Ref Env
        -
          Key: stack
          Value: !Sub ${AWS::StackName}
        -
          Key: owner
          Value: !Ref Owner
        -
          Key: application
          Value: !Ref Application
        -
          Key: component
          Value: !Ref Component
        -
          Key: pci_classification
          Value: !Ref PciClassification

Outputs:
  VpcLinkId:
    Description: Id the VpcLink
    Value: !Ref VpcLinkNLB03
    Export:
      Name: !Sub VpcLinkId${Name}