# Default NodeClass to provisione EC2 Nodes Amazon Linux 2 #
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: al2
  annotations:
    helm.sh/hook: post-install, post-upgrade
spec:
  amiSelectorTerms:
      - id: ami-01face754fdc60485 #ohio
      - id: ami-016e80ea1d0bc081f #sp
  amiFamily: AL2 # Amazon Linux 2
  instanceProfile: KarpenterNodeInstanceProfile-arch-eks-01-02 # this IAM Role needs be set in aws-auth configmap.
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "true"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/security-group: arch-eks-01-02
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required        
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        deleteOnTermination: true
  tags:
    cluster: arch-eks-01-02
    service: go-global
    squad: architecture
  userData: |
    #!/bin/bash
    echo "Installing SSM Agent"
    yum update -y
    yum install -y https://s3.us-east-1.amazonaws.com/amazon-ssm-us-east-1/latest/linux_amd64/amazon-ssm-agent.rpm
    systemctl enable amazon-ssm-agent
    systemctl start amazon-ssm-agent