AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template to Alarm SNS

Parameters:
  Env:
    Description: Execution environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - hml
      - prd
  EmailSNSEndpoint: 
    Type: String
    Default: eliezer.junior@xpto.tech
  TopicName:
    Type: String
    Default: incoming-byte-log-group-monitoring
  OwnerName:
    Type: String
    Default: architecture
    
Resources:
  TopicSNS:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: !Ref TopicName
      Subscription:
        - Endpoint: !Ref EmailSNSEndpoint
          Protocol: email
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: squad
          Value: architecture
        - Key: resource
          Value: sns-topic
        - Key: owner
          Value: !Ref OwnerName

  SNSEmailPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'SNS:GetTopicAttributes'
              - 'SNS:SetTopicAttributes'
              - 'SNS:AddPermission'
              - 'SNS:RemovePermission'
              - 'SNS:DeleteTopic'
              - 'SNS:Subscribe'
              - 'SNS:ListSubscriptionsByTopic'
              - 'SNS:Publish'
              - 'SNS:Receive'
            Condition:
              StringEquals:
                'aws:SourceOwner': !Sub ${AWS::AccountId}
            Effect: Allow
            Principal:
              AWS: '*'
            Resource: !Ref TopicSNS
            Sid: '0'
        Version: 2012-10-17
      Topics:
        - !Ref TopicSNS

  IncomingBytes:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 5
      AlarmActions:
        - !Ref TopicSNS
      AlarmDescription: >-
        Incoming bytes to CloudWatch is higher than normal
      AlarmName: IncomingBytes
      DatapointsToAlarm: 1
      MetricName: IncomingBytes
      Namespace: AWS/Logs
      Period: 900
      Statistic: Average
      Threshold: 15000
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: squad
          Value: architecture
        - Key: resource
          Value: cloudwatch-alarm
        - Key: owner
          Value: !Ref OwnerName

  IncomingBytesAnomaly:
    Type: 'AWS::CloudWatch::AnomalyDetector'
    Properties:
      MetricName: IncomingBytes
      Namespace: AWS/Logs
      Stat: Average

  IncomingBytesAnomalyAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      ComparisonOperator: GreaterThanUpperThreshold
      EvaluationPeriods: 5
      ActionsEnabled: true
      AlarmActions:
        - !Ref TopicSNS
      AlarmDescription: >-
        Incoming bytes to CloudWatch is higher than normal
      AlarmName: IncomingBytesAnomaly
      DatapointsToAlarm: 5
      Metrics:
        - Expression: 'ANOMALY_DETECTION_BAND(m1, 3)'
          Id: ad1
          Label: IncomingBytes(expected)
        - Id: m1
          MetricStat:
            Metric:
              MetricName: IncomingBytes
              Namespace: AWS/Logs
            Period: 300
            Stat: Average
      ThresholdMetricId: ad1
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: squad
          Value: architecture
        - Key: resource
          Value: cloudwatch-alarm
        - Key: owner
          Value: !Ref OwnerName