AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Policy Shared Secret Manager

Parameters:
  Versao:
    Type: String
    Default: 1.0
  Squad:
    Type: String
    Default: architecture
  Slack:
    Type: String
    Default: architecture
  Email:
    Type: String
    Default: architecture
  Env:
    Description: Execution environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - hml
      - prd
  ARNSecretManager:
    Type: String
    Default: arn:aws:secretsmanager:us-east-2:792192516784:secret:992382474575_arch-rds-02-access-ncEwuy
  ARNKms:
    Type: String
    Default: arn:aws:kms:us-east-2:792192516784:key/a902466b-95dd-4a92-b853-ec02805b4b50
  RoleAssociation:
    Type: String
    Default: OIDCRoleGoPayment

Resources:
  CustomPolicyForSecretManager:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: AllowGetSecretValue 
      Description: Customer managed policy for read access secret manager
      Path: '/'
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Sid: AllowGetSecretValue
            Action: 
              - 'secretsmanager:GetSecretValue'
              - 'secretsmanager:DescribeSecret'
            Resource: !Ref ARNSecretManager
          - Effect: Allow
            Sid: AllowKMSDecrypt
            Action: 
              - 'kms:Decrypt'
            Resource: !Ref ARNKms
      Roles: 
          - !Ref RoleAssociation

Outputs:
  CustomPolicyForSecretManager:
    Value: !GetAtt 'CustomPolicyForSecretManager.Arn'
