AWSTemplateFormatVersion: 2010-09-09
Description: Template to setup lifecycle configuration

Parameters:
  BucketName:
    Type: String
    Description: Name of the bucket

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Prefix: glacier
            Status: Enabled
            ExpirationInDays: 1827
            Transitions:
              - TransitionInDays: 90
                StorageClass: GLACIER
Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of S3 bucket with a lifecycle configuration.