AWSTemplateFormatVersion: '2010-09-09'
Description: Template create s3 bucket/policy

Parameters:
  Versao:
    Type: String
    Default: 0
  Env:
    Type: String
    AllowedValues:
      - dev
      - hml
      - prd
  S3BucketName:
    Description: Bucket Name
    Type: String

Resources:
  ConsoleBrazilStatementDocsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      Tags:
      - Key: env
        Value: !Ref Env
      - Key: stack
        Value: !Sub ${AWS::StackName}
      - Key: name
        Value: !Join ['', [!Ref S3BucketName, "-Bucket"]]
      - Key: resource
        Value: bucket-s3

  ConsoleBrazilStatementPierHTTPConnectionPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: ConsoleBrazilStatementDocsBucket
    Properties:
      Bucket: !Ref S3BucketName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:PutObjectAcl'
              - 's3:GetBucketLocation'
              - 's3:GetObjectTagging'
              - 's3:GetObjectVersion'
              - 's3:ListBucket'
              - 's3:ListBucketVersions'
            Resource:
              - !Sub arn:aws:s3:::${S3BucketName}
              - !Sub arn:aws:s3:::${S3BucketName}/*
            Principal:
              AWS: 
                - arn:aws:iam::971633816549:root

Outputs:
  BucketNameConsoleBrazilStatementDocsBucket:
    Value: !Ref ConsoleBrazilStatementDocsBucket
    Description: The name of the bucket
  BucketArnConsoleBrazilStatementDocsBucket: 
    Value: !GetAtt ConsoleBrazilStatementDocsBucket.Arn
    Description: The buckey ARN