AWSTemplateFormatVersion: "2010-09-09"
Description: A CloudFormation template to SSM maintenance windom

Parameters:
  SSMAutomationRole:
    Type: String
    Default: arn:aws:iam::992382474575:role/ssm-automation-role-eliezer
  SSMServiceRole:
    Type: String
    Description: AWS Service Role (this role already exists) 
    Default:  arn:aws:iam::992382474575:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM
  AutomationSSMStartTaskARN:
    Type: String
    Default: AWS-StartRdsInstance
  AutomationSSMStopTaskARN:
    Type: String
    Default: AWS-StopRdsInstance

Resources:
  MaintenanceWindowStart:
    Type: 'AWS::SSM::MaintenanceWindow'
    Properties:
      Name: rds_start
      Schedule: 'cron(0 9 ? * MON-FRI *)'
      ScheduleTimezone: "America/Sao_Paulo"
      Duration: 2 
      Cutoff: 1
      AllowUnassociatedTargets: yes 
      Description: 'This maintenance window to start a RDS'
      Tags:
        - Key:   stack
          Value:  !Sub '${AWS::StackName}'

  MaintenanceWindowStop:
    Type: 'AWS::SSM::MaintenanceWindow'
    Properties:
      Name: rds_stop
      Schedule: 'cron(0 23 ? * MON-FRI *)'
      ScheduleTimezone: "America/Sao_Paulo"
      Duration: 2 
      Cutoff: 1
      AllowUnassociatedTargets: yes 
      Description: 'This maintenance window to stop a RDS'
      Tags:
        - Key:   stack
          Value:  !Sub '${AWS::StackName}'

  StartMaintenanceWindowTarget:
    Type: AWS::SSM::MaintenanceWindowTarget
    Properties:
      Name: rds_ssm_automation_start
      Description: rds_ssm_automation_start
      WindowId: !Ref MaintenanceWindowStart
      ResourceType: INSTANCE
      Targets:
      - Key: tag:ssm_automation_start_stop
        Values:
        - true

  StopMaintenanceWindowTarget:
    Type: 'AWS::SSM::MaintenanceWindowTarget'
    Properties:
      Name: rds_ssm_automation_stop
      Description: rds_ssm_automation_stop
      WindowId: !Ref MaintenanceWindowStop
      ResourceType: INSTANCE
      Targets:
      - Key: tag:ssm_automation_start_stop
        Values:
        - true

  StartMaintenanceWindowTask:
    DependsOn: StartMaintenanceWindowTarget
    Type: AWS::SSM::MaintenanceWindowTask
    Properties:
      Name: start_rds_instances
      WindowId: !Ref MaintenanceWindowStart
      Targets: 
        - Key: WindowTargetIds
          Values:
          - !Ref StartMaintenanceWindowTarget
      TaskArn: !Ref AutomationSSMStartTaskARN
      ServiceRoleArn: !Ref SSMServiceRole
      TaskType: AUTOMATION
      TaskInvocationParameters:
        MaintenanceWindowAutomationParameters:
          Parameters:
            InstanceId:
              - "{{RESOURCE_ID}}"
            AutomationAssumeRole:
              - !Ref SSMAutomationRole
      Priority: 1
      MaxConcurrency: 1
      MaxErrors: 1

  StopMaintenanceWindowTask:
    DependsOn: StopMaintenanceWindowTarget
    Type: AWS::SSM::MaintenanceWindowTask
    Properties:
      Name: stop_rds_instances
      WindowId: !Ref MaintenanceWindowStop
      Targets: 
        - Key: WindowTargetIds
          Values:
          - !Ref StopMaintenanceWindowTarget
      TaskArn: !Ref AutomationSSMStopTaskARN
      ServiceRoleArn: !Ref SSMServiceRole
      TaskType: AUTOMATION
      TaskInvocationParameters:
        MaintenanceWindowAutomationParameters:
          Parameters:
            InstanceId:
              - "{{RESOURCE_ID}}"
            AutomationAssumeRole:
              - !Ref SSMAutomationRole
      Priority: 1
      MaxConcurrency: 1
      MaxErrors: 1
