AWSTemplateFormatVersion: "2010-09-09"
Description: Role AWSResilienceHubRoles.

Parameters:
  ManagedPolicyParameterOne:
    Description: Inform policy ARN (opcional)
    Type: String 
    Default: arn:aws:iam::aws:policy/AWSResilienceHubAsssessmentExecutionPolicy
  component:
    Description:    Please specify the Component. Used for tagging
    Type:           String
    Default:        Role
  owner:
    Description:    Please specify the Owner. Used for tagging  
    Type:           String
    Default:        architecture 

Conditions:
  IsManagedPolicyParameterOne:    !Not [!Equals [ !Ref ManagedPolicyParameterOne, "" ]]

Resources:
  AWSResilienceHubRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "AWSResilienceHubRole-${AWS::AccountId}"
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: resiliencehub.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !If [ IsManagedPolicyParameterOne, !Ref ManagedPolicyParameterOne, !Ref 'AWS::NoValue' ]
      Tags:
        - Key:    stack
          Value:  !Sub '${AWS::StackName}'
        - Key:    owner
          Value:  !Ref owner
        - Key:    component
          Value:  !Ref component          

Outputs:
  AWSResilienceHubRole:
    Value: !GetAtt 'AWSResilienceHubRole.Arn'